import {
  ArrowUpDown,
  BaggageClaim,
  BookOpen,
  BriefcaseBusiness,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleArrowDown,
  CircleArrowUp,
  Dumbbell,
  Eye,
  EyeClosed,
  Gift,
  HeartPulse,
  Home,
  LogIn,
  LogOut,
  Mail,
  Mailbox,
  PawPrint,
  PiggyBank,
  ReceiptText,
  Search,
  ShoppingCart,
  SquarePen,
  Tag,
  Ticket,
  ToolCase,
  Trash2,
  UserRound,
  UserRoundPlus,
  Utensils,
  Wallet,
  X,
  Lock,
  MinusCircle,
  Plus,
} from "lucide-react";

export const CATEGORY_ICON_OPTIONS = [
  { id: "baggage-claim", Icon: BaggageClaim },
  { id: "book-open", Icon: BookOpen },
  { id: "briefcase-business", Icon: BriefcaseBusiness },
  { id: "car-front", Icon: CarFront },
  { id: "gift", Icon: Gift },
  { id: "heart-pulse", Icon: HeartPulse },
  { id: "house", Icon: Home },
  { id: "utensils", Icon: Utensils },
  { id: "ticket", Icon: Ticket },
  { id: "tool-case", Icon: ToolCase },
  { id: "paw-print", Icon: PawPrint },
  { id: "piggy-bank", Icon: PiggyBank },
  { id: "receipt-text", Icon: ReceiptText },
  { id: "shopping-cart", Icon: ShoppingCart },
  { id: "dumbbell", Icon: Dumbbell },
  { id: "mailbox", Icon: Mailbox },
] as const;

export const ICON_OPTIONS = [
  ...CATEGORY_ICON_OPTIONS,
  { id: "check", Icon: Check },
  { id: "arrow-up-down", Icon: ArrowUpDown },
  { id: "chevron-down", Icon: ChevronDown },
  { id: "chevron-left", Icon: ChevronLeft },
  { id: "chevron-right", Icon: ChevronRight },
  { id: "chevron-up", Icon: ChevronUp },
  { id: "circle-arrow-down", Icon: CircleArrowDown },
  { id: "circle-arrow-up", Icon: CircleArrowUp },
  { id: "eye", Icon: Eye },
  { id: "eye-closed", Icon: EyeClosed },
  { id: "log-in", Icon: LogIn },
  { id: "log-out", Icon: LogOut },
  { id: "lock", Icon: Lock },
  { id: "mail", Icon: Mail },
  { id: "plus", Icon: Plus },
  { id: "search", Icon: Search },
  { id: "square-pen", Icon: SquarePen },
  { id: "trash", Icon: Trash2 },
  { id: "user-round", Icon: UserRound },
  { id: "user-round-plus", Icon: UserRoundPlus },
  { id: "wallet", Icon: Wallet },
  { id: "tag", Icon: Tag },
  { id: "minus", Icon: MinusCircle },
  { id: "x", Icon: X },
] as const;
